@startuml
!include style.puml
skinparam BoxPadding 20

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ExpenseBookParser" as ExpenseBookParser LOGIC_COLOR
participant "command:ListExpenseByCategoryCommand" as ListExpenseByCategoryCommand LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant "pred:CategoryContainsKeywordsPredicate" as CategoryContainsKeywordsPredicate MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
participant "fe:FilteredList" as FilteredList MODEL_COLOR
end box

[-> MainWindow
activate MainWindow

MainWindow -> LogicManager : execute("filter-c food")
activate LogicManager

LogicManager -> ExpenseBookParser : parseCommand("filter-c food")
activate ExpenseBookParser

create ListExpenseByCategoryCommand
ExpenseBookParser -> ListExpenseByCategoryCommand : parse("food")
activate ListExpenseByCategoryCommand

create CategoryContainsKeywordsPredicate
ListExpenseByCategoryCommand -> CategoryContainsKeywordsPredicate
activate CategoryContainsKeywordsPredicate

CategoryContainsKeywordsPredicate -> ListExpenseByCategoryCommand : pred
deactivate CategoryContainsKeywordsPredicate

ListExpenseByCategoryCommand --> ExpenseBookParser : command
deactivate ListExpenseByCategoryCommand

ExpenseBookParser --> LogicManager : command

LogicManager -> ListExpenseByCategoryCommand : execute(Model)
activate ListExpenseByCategoryCommand

ListExpenseByCategoryCommand -> Model : updateFilteredExpenseList(pred)
activate Model

Model -> FilteredList : setPredicate(pred)

Model --> ListExpenseByCategoryCommand
deactivate Model

ListExpenseByCategoryCommand --> LogicManager : result
deactivate ListExpenseByCategoryCommand
ListExpenseByCategoryCommand -[hidden]-> LogicManager : result
destroy ListExpenseByCategoryCommand

MainWindow <--LogicManager : result
deactivate LogicManager

[<-- MainWindow
deactivate MainWindow

@enduml
