@startuml
!include style.puml
skinparam BoxPadding 20

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ExpenseBookParser" as ExpenseBookParser LOGIC_COLOR
participant "command:ListExpenseByDateCommand" as ListExpenseByDateCommand LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant "pred:DateContainsKeywordsPredicate" as DateContainsKeywordsPredicate MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
participant "fe:FilteredList" as FilteredList MODEL_COLOR
end box

[-> MainWindow
activate MainWindow

MainWindow -> LogicManager : execute("filter-t 2020-12-12")
activate LogicManager

LogicManager -> ExpenseBookParser : parseCommand("filter-t 2020-12-12")
activate ExpenseBookParser

create ListExpenseByDateCommand
ExpenseBookParser -> ListExpenseByDateCommand : parse("2020-12-12")
activate ListExpenseByDateCommand

create DateContainsKeywordsPredicate
ListExpenseByDateCommand -> DateContainsKeywordsPredicate
activate DateContainsKeywordsPredicate

DateContainsKeywordsPredicate -> ListExpenseByDateCommand : pred
deactivate DateContainsKeywordsPredicate

ListExpenseByDateCommand --> ExpenseBookParser : command
deactivate ListExpenseByDateCommand

ExpenseBookParser --> LogicManager : command

LogicManager -> ListExpenseByDateCommand : execute(Model)
activate ListExpenseByDateCommand

ListExpenseByDateCommand -> Model : updateFilteredExpenseList(pred)
activate Model

Model -> FilteredList : setPredicate(pred)

Model --> ListExpenseByDateCommand
deactivate Model

ListExpenseByDateCommand --> LogicManager : result
deactivate ListExpenseByDateCommand
ListExpenseByDateCommand -[hidden]-> LogicManager : result
destroy ListExpenseByDateCommand

MainWindow <--LogicManager : result
deactivate LogicManager

[<-- MainWindow
deactivate MainWindow

@enduml
