@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyExpenseBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class ExpenseBook
Class ReadOnlyExpenseBook
Class Model
Class ExpenseModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Expense {
Class Expense
Class Amount
Class Category
Class Date
Class Description
Class ExpenseList
Class Budget
Class Currency
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ExpenseBook .up.|> ReadOnlyExpenseBook

ExpenseModelManager .up.|> Model
Model .right.> ObservableList
ExpenseModelManager o--> "1" ExpenseBook
ExpenseModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ExpenseBook *--> "1" ExpenseList
ExpenseBook *--> "1" Budget
ExpenseBook *--> "1" Currency
ExpenseList o--> "*" Expense
Expense *--> Amount
Expense *--> Date
Expense *--> Category
Expense *--> Description

Amount -[hidden]right-> Category
Category -[hidden]right-> Date
Date -[hidden]right-> Description

ExpenseModelManager -->"1" Expense : manage
@enduml
