@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Expense {
Class Expense
Class Amount
Class Category
Class Date
Class Description
Class UniqueExpenseList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ExpenseBook .up.|> ReadOnlyExpenseBook

ExpenseModelManager .up.|> Model
Model .right.> ObservableList
ExpenseModelManager o--> "1" AddressBook
ExpenseModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ExpenseBook *--> "1" UniqueExpenseList
UniqueExpenseList o--> "*" Expense
Expense *--> Name
Expense *--> Phone
Expense *--> Email
Expense *--> Address
Expense *--> "*" Tag

Amount -[hidden]right-> Category
Category -[hidden]right-> Date
Date -[hidden]right-> Description

ExpenseModelManager -->"1" Expense : filtered list
@enduml
