@startuml
start
:User executes a SortByTimeCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command word is a valid SortByTimeCommand command word])
    :Create an SortByTimeCommandParser;
    :SortByTimeCommandParser parses the rest of the user input;
    if () then ([the input order is a valid order(ascending or descending)])
        :Create a new SortByTimeCommand;
    else ([else])
        :throw an exception;
        :update UI to notify user;
    endif
else ([else])
    :throw an exception;
    :update UI to notify user;
endif
stop
@enduml