@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ExpenseBookParser" as ExpenseBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedExpenseBook" as VersionedExpenseBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ExpenseBookParser : parseCommand(undo)
activate ExpenseBookParser

create UndoCommand
ExpenseBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> ExpenseBookParser
deactivate UndoCommand

ExpenseBookParser --> LogicManager : u
deactivate ExpenseBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoExpenseBook()
activate Model

Model -> VersionedExpenseBook : undo()
activate VersionedExpenseBook

VersionedExpenseBook -> VersionedExpenseBook :resetData(ReadOnlyExpenseBook)
VersionedExpenseBook --> Model :
deactivate VersionedAddressBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
